### ISSUE TITLE
Timestamp - icon choice

### ISSUE THREAD

**Issue by mateuszwilczek** [pmario/lucide-tiddlywiki-plugin#4]
I would use the Lucide `timer` and `timer-off`:
![image](https://github.com/user-attachments/assets/83204c42-00c9-4cd8-bbf7-36325ac2cba0)

Instead of the custom:
![image](https://github.com/user-attachments/assets/3fd73331-d28b-4c5b-a465-14a6acef5384)

For the _on_ icon, I don't see a reason to use something different than Lucide's `timer`, it is clear enough.

For the _off_ icon, I think Lucide's strikethrough icon is clearer at small sizes and bolder variants, where the "pause" inside might be too small to see it properly.

**Comment by pmario** [comment]
See: timer-eye.html -> [Icon Gallery](https://pmario.github.io/lucide-tiddlywiki-plugin/timer-eye.html#Icon%20Gallery:%5B%5BIcon%20Gallery%5D%5D) - from branch `timer`

![grafik](https://github.com/user-attachments/assets/7a3cd005-adea-4809-ae13-229331b3fbdc)

**Comment by pmario** [comment]
I did push a new WIP wiki **timer-eye.html** -> [Icon Gallery](https://pmario.github.io/lucide-tiddlywiki-plugin/timer-eye.html#Icon%20Gallery:%5B%5BIcon%20Gallery%5D%5D) - from branch `timer`. It only contains the core-plugin

As requested by @mateuszwilczek I did change 

- the "timer" and "timer-off" icons, to suppress the modified timestamp. 
- The "preview-open" and "preview-closed" ... Where the preview-open now is the lucide-eye-off icon

**NEW timer-eye-hmtl**

![grafik](https://github.com/user-attachments/assets/7a3cd005-adea-4809-ae13-229331b3fbdc)

@jermolene **Decisions needed:**

The **current** version at https://pmario.github.io/lucide-tiddlywiki-plugin/ looks like this:

![grafik](https://github.com/user-attachments/assets/2085d5e2-2690-4cf6-a941-576473ee11f7)

1.  We need a decision, which icons should be **used by default** 
    - Those from NEW timer-eyes or the current ones

2. Should the **current** eye-closed ![grafik](https://github.com/user-attachments/assets/a02546a0-f4a6-402c-bdd2-7b0201293f4c) be shipped with the core, to give plugin authors the possibility to use that icon. 
    - If the eye-off  icon ![grafik](https://github.com/user-attachments/assets/ec1b980e-9aaa-448b-851f-59e87ab15597) is used by default, that may cause problems for plugin authors. That's why I think the "eye-closed" icon should be shipped with the core. 

-------

**Timer Icons Decisions**

3. The same decisions are required for **the "timer" iocns**

**Comment by pmario** [comment]
>The only advantage of restricting ourselves to the standard Lucide set would be to avoid the work of making our own icons. Personally, I find making icons relatively straightforward and quite enjoyable.

We do already use 55 custom made TW icons, that are compatible with Lucide. See: https://github.com/pmario/lucide-tiddlywiki-plugin/tree/main/origin -- I did create all of them in a way, that they are very similar to the current iconography. 

There is a [mapping-configuration](https://github.com/pmario/lucide-tiddlywiki-plugin/blob/main/scripts/config/tiddlywiki-mappings.json), which is used by the build process. This mapper makes it easy to "map" every Lucide or custom icon to a TW `$:/core/images/*` tiddler.

The decisions we need is: 

Do we want: **current**: ![grafik](https://github.com/user-attachments/assets/e71b2d31-244f-4f71-97cb-fa0ad7993f7a) or **new**: ![grafik](https://github.com/user-attachments/assets/ef3e4eb8-f4a4-44b9-856d-7bcfd3043955)

and

Do we want: **current** ![grafik](https://github.com/user-attachments/assets/100e0e0d-8f23-411b-8c92-a4170df4fee6) or **new** ![grafik](https://github.com/user-attachments/assets/98f37b6d-8d13-4e21-be52-bdb2358d49b6)

Where **current** is TW custom made and **new** is Lucide 

------

Since I did create the very firs version the Lucide upstream project did already include a new icon, which was probably inspired by TW. 

![grafik](https://github.com/user-attachments/assets/caddbeaf-e3e7-41a5-a698-06685d448bb4)

So there is a chance, that some of our icons may make the way upstream. **But** I did not create any PRs yet.

**Comment by pmario** [comment]
><$transclude $tiddler="$:/core/images/timestamp-on" stroke-width="2" size="40pt"/>

stroke is set to "none" by default. It needs a color. stroke-width should be between 0 and 1

See: https://pmario.github.io/lucide-tiddlywiki-plugin/timer-eye.html#test-dynamic-thickness

```
<$transclude $tiddler="$:/core/images/timestamp-on" stroke-width="2" size="40pt" stroke="black"/>
```

**Comment by pmario** [comment]
```
<$transclude $tiddler="$:/core/images/timestamp-on" stroke-width="0" size="40pt" stroke="black"/>

<$transclude $tiddler="$:/core/images/timestamp-on" stroke-width="1" size="40pt" stroke="black"/>

----

<$transclude $tiddler="$:/core/images/timestamp-on" stroke-width="1" size="40pt" stroke="white"/>

<$transclude $tiddler="$:/core/images/timestamp-on" stroke-width="1" size="40pt" stroke="pink"/>
```

![grafik](https://github.com/user-attachments/assets/6e03e464-d02c-4a7b-8e63-388d15edfbc9)

**Comment by Jermolene** [comment]
Thanks @pmario my vote would be to keep the current preview icon, and to switch to the new timer icons; the Lucide versions look cleaner, and I think the "slash" more clearly indicates the state than the existing "pause" symbol.

**Comment by pmario** [comment]
OK.

**Comment by pmario** [comment]
latest versions pushed

- https://pmario.github.io/lucide-tiddlywiki-plugin
- https://pmario.github.io/lucide-tiddlywiki-plugin/lucide-all.html
